// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hopac.Extras")>]
[<assembly: AssemblyProductAttribute("Hopac.Extras")>]
[<assembly: AssemblyDescriptionAttribute("The Hopac.Extras project contains useful abstractions implemented with Hopac.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hopac.Extras"
    let [<Literal>] AssemblyProduct = "Hopac.Extras"
    let [<Literal>] AssemblyDescription = "The Hopac.Extras project contains useful abstractions implemented with Hopac."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
